add protocol fee to snapshot
invariant-labs/stats pull request #107
Opened 2024-12-05 21:52 UTC by zielvna

2024-12-06 05:33 UTC, wojciech-cichocki requested changes

2024-12-06 05:33 UTC, wojciech-cichocki commented on eclipse/src/snap.ts
> +          tokenBNFromBeginning: "0",
I'm not sure if the parametr `FromBeginning` is adequate for how it is being used with the fee

2024-12-06 10:03 UTC, none00y approved these changes

2024-12-09 11:03 UTC, wojciech-cichocki approved these changes

2024-12-09 11:04 UTC, merged